export class Student {

  constructor(
    public id: number,
    public name: string,
    public Age: string,
    public University: string,
    public UniversityType: string,
    public Difficulty: string,
    public CourseCount: string,
    public GPA: string,
    public Major: string,
    public GraduatingYear: string,
    public Sports: string,
    public Cultural: string,
    public Arts: string,
    public Travel: string,
    public UW: number,
    public SeattleU: number,
    public BellevueCollege: number,
    public Target: number,
    public Nordstrom: number,
    public Costco: number,
    public Starbucks: number,
    public PikePlace: number,
    public WholeFoods: number,
    public Microsoft: number,
    public Amazon: number,
    public Boeing: number,
    public MtRainier: number,
    public RattlesnakeRidge: number,
    public LakeWashington: number,
    public MuseumOfFlight: number,
    public PacificScienceCenter: number,
    public Chinatown: number,
    public LGBTQPrideDay: number,
    public SeattleCannabisDay: number,
    public SeattleArtMuseum: number
  ) { }
}